vpc_cidr                    = "10.0.0.0/16"
redshift_subnet_cidr_first  = "10.0.1.0/24"
redshift_subnet_cidr_second = "10.0.2.0/24"
rs_cluster_identifier       = "rst-cluster"
rs_database_name            = "rst_cluster"
rs_master_username          = "sysadmin"
rs_nodetype                 = "dc2.large"
rs_cluster_type             = "single-node"
